# Generated by Django 5.0 on 2023-12-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
